drop table if exists prod.task;
drop table if exists prod.task_state;
drop table if exists prod.board;

drop schema if exists prod;

create schema prod;

create table prod.board(
    id int primary key generated by default as identity,
    name varchar not null,
    is_deleted boolean not null
);